module FoldersHelper
  FOLDER_TYPE_INBOX =1
  FOLDER_TYPE_NEXT =2
  FOLDER_TYPE_PROJCET =3
  FOLDER_TYPE_WAITING =4
  FOLDER_TYPE_SOMEDAY =5
  FOLDER_TYPE_SCHEDULE =6
  FOLDER_TYPE_TRASH =7
  FOLDER_TYPE_USER =10

end
